/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.ismail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Product service. Represents a row in the &quot;Product_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.ismail.model.impl.ProductModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.ismail.model.impl.ProductImpl</code>.
 * </p>
 *
 * @author "user"
 * @see Product
 * @generated
 */
@ProviderType
public interface ProductModel
	extends BaseModel<Product>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel, TrashedModel, WorkflowedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product model instance should use the {@link Product} interface instead.
	 */

	/**
	 * Returns the primary key of this product.
	 *
	 * @return the primary key of this product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product.
	 *
	 * @param primaryKey the primary key of this product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this product.
	 *
	 * @return the mvcc version of this product
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this product.
	 *
	 * @param mvccVersion the mvcc version of this product
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this product.
	 *
	 * @return the uuid of this product
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this product.
	 *
	 * @param uuid the uuid of this product
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the product ID of this product.
	 *
	 * @return the product ID of this product
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product.
	 *
	 * @param productId the product ID of this product
	 */
	public void setProductId(long productId);

	/**
	 * Returns the product name of this product.
	 *
	 * @return the product name of this product
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this product.
	 *
	 * @param productName the product name of this product
	 */
	public void setProductName(String productName);

	/**
	 * Returns the number of products of this product.
	 *
	 * @return the number of products of this product
	 */
	public int getNumberOfProducts();

	/**
	 * Sets the number of products of this product.
	 *
	 * @param numberOfProducts the number of products of this product
	 */
	public void setNumberOfProducts(int numberOfProducts);

	/**
	 * Returns the attachment of this product.
	 *
	 * @return the attachment of this product
	 */
	@AutoEscape
	public String getAttachment();

	/**
	 * Sets the attachment of this product.
	 *
	 * @param attachment the attachment of this product
	 */
	public void setAttachment(String attachment);

	/**
	 * Returns the group ID of this product.
	 *
	 * @return the group ID of this product
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this product.
	 *
	 * @param groupId the group ID of this product
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this product.
	 *
	 * @return the company ID of this product
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product.
	 *
	 * @param companyId the company ID of this product
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product.
	 *
	 * @return the user ID of this product
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this product.
	 *
	 * @param userId the user ID of this product
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product.
	 *
	 * @return the user uuid of this product
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this product.
	 *
	 * @param userUuid the user uuid of this product
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this product.
	 *
	 * @return the user name of this product
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this product.
	 *
	 * @param userName the user name of this product
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this product.
	 *
	 * @return the create date of this product
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product.
	 *
	 * @param createDate the create date of this product
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product.
	 *
	 * @return the modified date of this product
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product.
	 *
	 * @param modifiedDate the modified date of this product
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the url title of this product.
	 *
	 * @return the url title of this product
	 */
	@AutoEscape
	public String getUrlTitle();

	/**
	 * Sets the url title of this product.
	 *
	 * @param urlTitle the url title of this product
	 */
	public void setUrlTitle(String urlTitle);

	/**
	 * Returns the product title name of this product.
	 *
	 * @return the product title name of this product
	 */
	@AutoEscape
	public String getProductTitleName();

	/**
	 * Sets the product title name of this product.
	 *
	 * @param productTitleName the product title name of this product
	 */
	public void setProductTitleName(String productTitleName);

	/**
	 * Returns the product summary name of this product.
	 *
	 * @return the product summary name of this product
	 */
	@AutoEscape
	public String getProductSummaryName();

	/**
	 * Sets the product summary name of this product.
	 *
	 * @param productSummaryName the product summary name of this product
	 */
	public void setProductSummaryName(String productSummaryName);

	/**
	 * Returns the status of this product.
	 *
	 * @return the status of this product
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this product.
	 *
	 * @param status the status of this product
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this product.
	 *
	 * @return the status by user ID of this product
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this product.
	 *
	 * @param statusByUserId the status by user ID of this product
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this product.
	 *
	 * @return the status by user uuid of this product
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this product.
	 *
	 * @param statusByUserUuid the status by user uuid of this product
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this product.
	 *
	 * @return the status by user name of this product
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this product.
	 *
	 * @param statusByUserName the status by user name of this product
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this product.
	 *
	 * @return the status date of this product
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this product.
	 *
	 * @param statusDate the status date of this product
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the trash entry created when this product was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this product.
	 *
	 * @return the trash entry created when this product was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this product.
	 *
	 * @return the class primary key of the trash entry for this product
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this product.
	 *
	 * @return the trash handler for this product
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this product is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this product is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this product is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this product is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this product is approved.
	 *
	 * @return <code>true</code> if this product is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this product is denied.
	 *
	 * @return <code>true</code> if this product is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this product is a draft.
	 *
	 * @return <code>true</code> if this product is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this product is expired.
	 *
	 * @return <code>true</code> if this product is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this product is inactive.
	 *
	 * @return <code>true</code> if this product is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this product is incomplete.
	 *
	 * @return <code>true</code> if this product is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this product is pending.
	 *
	 * @return <code>true</code> if this product is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this product is scheduled.
	 *
	 * @return <code>true</code> if this product is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}